/*
 * Port_PBcfg.c
 *
 *      Author: Eslam
 */


#import "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

/* PB structure used with Port_Init API */
const Port_ConfigType Port_Configuration=  {

					        PORTA_ID,PORT_PIN0,PORTA_PIN0_DDR,PORTA_PIN0_CR,
					 		PORTA_ID,PORT_PIN1,PORTA_PIN1_DDR,PORTA_PIN1_CR,
					 		PORTA_ID,PORT_PIN2,PORTA_PIN2_DDR,PORTA_PIN2_CR,
					 		PORTA_ID,PORT_PIN3,PORTA_PIN3_DDR,PORTA_PIN3_CR,
					 		PORTA_ID,PORT_PIN4,PORTA_PIN4_DDR,PORTA_PIN4_CR,
					 		PORTA_ID,PORT_PIN5,PORTA_PIN5_DDR,PORTA_PIN5_CR,
					 		PORTA_ID,PORT_PIN6,PORTA_PIN6_DDR,PORTA_PIN6_CR,
					 		PORTA_ID,PORT_PIN7,PORTA_PIN7_DDR,PORTA_PIN7_CR,

					 		PORTB_ID,PORT_PIN0,PORTB_PIN0_DDR,PORTB_PIN0_CR,
					 		PORTB_ID,PORT_PIN1,PORTB_PIN1_DDR,PORTB_PIN1_CR,
					 		PORTB_ID,PORT_PIN2,PORTB_PIN2_DDR,PORTB_PIN2_CR,
					 		PORTB_ID,PORT_PIN3,PORTB_PIN3_DDR,PORTB_PIN3_CR,
					 		PORTB_ID,PORT_PIN4,PORTB_PIN4_DDR,PORTB_PIN4_CR,
					 		PORTB_ID,PORT_PIN5,PORTB_PIN5_DDR,PORTB_PIN5_CR,
					 		PORTB_ID,PORT_PIN6,PORTB_PIN6_DDR,PORTB_PIN6_CR,
					 		PORTB_ID,PORT_PIN7,PORTB_PIN7_DDR,PORTB_PIN7_CR,

					 		PORTC_ID,PORT_PIN0,PORTC_PIN0_DDR,PORTC_PIN0_CR,
					 		PORTC_ID,PORT_PIN1,PORTC_PIN1_DDR,PORTC_PIN1_CR,
					 		PORTC_ID,PORT_PIN2,PORTC_PIN2_DDR,PORTC_PIN2_CR,
					 		PORTC_ID,PORT_PIN3,PORTC_PIN3_DDR,PORTC_PIN3_CR,
					 		PORTC_ID,PORT_PIN4,PORTC_PIN4_DDR,PORTC_PIN4_CR,
					 		PORTC_ID,PORT_PIN5,PORTC_PIN5_DDR,PORTC_PIN5_CR,
					 		PORTC_ID,PORT_PIN6,PORTC_PIN6_DDR,PORTC_PIN6_CR,
					 		PORTC_ID,PORT_PIN7,PORTC_PIN7_DDR,PORTC_PIN7_CR,

					 		PORTD_ID,PORT_PIN0,PORTD_PIN0_DDR,PORTD_PIN0_CR,
					 		PORTD_ID,PORT_PIN1,PORTD_PIN1_DDR,PORTD_PIN1_CR,
					 		PORTD_ID,PORT_PIN2,PORTD_PIN2_DDR,PORTD_PIN2_CR,
					 		PORTD_ID,PORT_PIN3,PORTD_PIN3_DDR,PORTD_PIN3_CR,
					 		PORTD_ID,PORT_PIN4,PORTD_PIN4_DDR,PORTD_PIN4_CR,
					 		PORTD_ID,PORT_PIN5,PORTD_PIN5_DDR,PORTD_PIN5_CR,
					 		PORTD_ID,PORT_PIN6,PORTD_PIN6_DDR,PORTD_PIN6_CR,
					 		PORTD_ID,PORT_PIN7,PORTD_PIN7_DDR,PORTD_PIN7_CR,

								   };
